### ISSUE TITLE
adding sound to the game

### ISSUE THREAD

**Issue by endurance21** [frappelatte28/2D_Breakout_game#1]
## Adding  sounds to projects makes it more alive and  makes a good connection to end users , being said that  we can also include sound to our game ! 
we can play a sound : 

*  every time a collision occurs 
* game over 

for this we can use  a awesome  javascript library [p5.sound](https://github.com/processing/p5.js-sound)  { ps : promotions :p} 

[here is the documentation we can use to play sound]( https://p5js.org/examples/sound-load-and-play-sound.html) --> check it out , this library have awesome show case examples underlying all the fundamentals and paves a intuitive way to add sounds in your projects!

**Comment by frappelatte28** [comment]
Thank You @endurance21 for your kind suggestion

**Comment by frappelatte28** [comment]
That seems insightful, I will check it out.

**Comment by endurance21** [comment]
@frappelatte28   as i can see , your game lacks modularization of code , hope to see that in  next update !
however your game logics seems very fundamental and interesting !

**Comment by frappelatte28** [comment]
@endurance21 I appreciate your concern towards modularizing the code we will make sure of that in coming updates and we are looking for some volunteering, i would welcome a PULL REQUEST for the same, if you can.
And yes! Being fundamental is what i like to be.

**Comment by endurance21** [comment]
@frappelatte28  i would love to contribute for the same ! 
hope we will  soon meet at my  PULL REQUEST discussions !
